export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const GET_TODO_ITEMS = 'GET_TODO_ITEMS';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';

export const SET_TODO_COMPLETED = 'SET_TODO_COMPLETED';
export const SET_TODO_NOT_COMPLETED = 'SET_TODO_NOT_COMPLETED';
export const SET_TODO_START_EDITING = 'SET_TODO_START_EDITING';
export const SET_TODO_STOP_EDITING = 'SET_TODO_STOP_EDITING';
